FROM alpine:3.6

ARG SERVICE_USER
ARG SERVICE_HOME
ARG SERVICE_PORT

ENV SERVICE_USER ${SERVICE_USER:-mongo}
ENV SERVICE_HOME ${SERVICE_HOME:-/data/db}
ENV SERVICE_PORT ${SERVICE_PORT:-27017}

RUN \
  mkdir -p ${SERVICE_HOME} && \
  adduser -h ${SERVICE_HOME} -s /sbin/nologin -u 1000 -D ${SERVICE_USER} && \
  chown -R ${SERVICE_USER}:${SERVICE_USER} ${SERVICE_HOME} && \
  echo http://dl-4.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && \
  apk add --no-cache \
    dumb-init \
    mongodb

USER    ${SERVICE_USER}
WORKDIR ${SERVICE_HOME}
VOLUME  ${SERVICE_HOME}
EXPOSE  ${SERVICE_PORT}

CMD mongod \
  --port ${SERVICE_PORT} \
  --dbpath ${SERVICE_HOME} \
  && echo 'Mongo started'

