version: '3'
services:
  mentoring-node-app:
    build:
      context: .
    ports:
      - "8081:8081"
    volumes:
      - .:/www/target/
      - /www/target/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: mongo:latest
    ports:
      - "26017:27017"
#    build:
#      context: .
#      dockerfile: Dockerfile-mongo
#    ports:
#      - "26017:27017"
