version: '3'
services:
  mentoring-node-app:
    build:
      context: .
      dockerfile: Dockerfile-node_app
    ports:
      - "8081:8081"
    volumes:
      - .:/www/target/
      - /www/target/node_modules
    depends_on:
      - "postgres"
  postgres:
    image: postgres:9.6-alpine
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "4432:5432"
    environment:
      POSTGRES_DB: 'mentoring'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
