FROM node:8.0.0-alpine

WORKDIR /www/target
COPY . .

RUN mkdir /www/tmp
COPY package.json /www/tmp/
WORKDIR /www/tmp
RUN npm i -g yarn && yarn global add nodemon babel-cli babel-core  && yarn install

WORKDIR /www/target
RUN mkdir -p node_modules
RUN cp -R /www/tmp/node_modules/* /www/target/node_modules

ENV PORT=8081
EXPOSE 8081
CMD npm start
