version: '3'
services:
  mentoring-node-app:
    build:
      context: .
    ports:
      - "8081:8081"
    volumes:
      - .:/www/target/
      - /www/target/node_modules
    depends_on:
      - "postgres"
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "4432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
