definitions:
  Product:
    type: object
    properties:
      name:
        type: string
        example: Bumetanide
      brand:
        type: string
        example: Bumetanide
      price:
        type: string
        example: $42.28
      isbn:
        type: string
        example: 158995707-5
      company:
        type: string
        example: Mylan Institutional Inc.
